const formatCurrency = value => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value || 0);
const formatDate = value => value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium' }).format(new Date(`${value}T00:00:00`)) : '—';
const showToast = (message, type = 'error') => { const previous = document.querySelector('.toast'); if (previous) previous.remove(); const toast = document.createElement('div'); toast.className = `toast ${type}`; toast.textContent = message; document.body.append(toast); setTimeout(() => toast.remove(), 4200); };
const getSession = key => JSON.parse(sessionStorage.getItem(key) || 'null');
const setSession = (key, value) => sessionStorage.setItem(key, JSON.stringify(value));
const clearSession = key => sessionStorage.removeItem(key);
const currentUser = () => getSession('currentUser');
const isAdmin = () => currentUser()?.role === 'ADMIN';
const loadComponent = async (id, file) => { const host = document.getElementById(id); if (!host) return; try { host.innerHTML = await (await fetch(`components/${file}`)).text(); } catch { host.innerHTML = ''; } };
function renderAccountActions() { const actions = document.querySelector('.nav-actions'); if (!actions) return; const user = currentUser(); if (!user) { actions.innerHTML = '<a class="nav-login" href="login.html">Đăng nhập</a><a class="nav-signup" href="register.html">Đăng ký</a>'; return; } const roleLabel = user.role === 'ADMIN' ? 'Quản trị viên' : 'Khách hàng'; const initial = (user.fullName || 'U').trim().charAt(0).toUpperCase(); actions.innerHTML = `${user.role === 'ADMIN' ? '<a class="nav-dashboard" href="dashboard.html">Dashboard</a>' : ''}<div class="account-menu"><button class="account-trigger" type="button" aria-expanded="false" aria-haspopup="true"><span class="account-avatar" aria-hidden="true">${initial}</span><span class="account-trigger-name nav-user">${user.fullName}</span><i class="fa-solid fa-chevron-down" aria-hidden="true"></i></button><div class="account-dropdown" role="menu"><div class="account-summary"><span class="account-avatar account-avatar-large" aria-hidden="true">${initial}</span><div><strong>${user.fullName}</strong><span>${roleLabel}</span><small>${user.phone}</small></div></div><div class="account-menu-divider"></div><div class="account-menu-links"><a class="account-menu-item" href="profile.html" role="menuitem"><i class="fa-regular fa-user"></i>Hồ sơ cá nhân</a><a class="account-menu-item" href="history.html" role="menuitem"><i class="fa-solid fa-ticket"></i>Vé của tôi</a><a class="account-menu-item" href="history.html" role="menuitem"><i class="fa-solid fa-clock-rotate-left"></i>Lịch sử đặt vé</a><a class="account-menu-item" href="#site-support" role="menuitem"><i class="fa-regular fa-circle-question"></i>Hỗ trợ</a></div><div class="account-menu-divider"></div><button class="account-menu-item account-logout nav-logout" type="button" role="menuitem"><i class="fa-solid fa-arrow-right-from-bracket"></i>Đăng xuất</button></div></div>`; actions.querySelector('.nav-logout').addEventListener('click', () => { clearSession('currentUser'); location.href = 'index.html'; }); const menu = actions.querySelector('.account-menu'); const trigger = actions.querySelector('.account-trigger'); const closeMenu = () => { menu.classList.remove('is-open'); trigger.setAttribute('aria-expanded', 'false'); }; trigger.addEventListener('click', event => { event.stopPropagation(); const isOpen = menu.classList.toggle('is-open'); trigger.setAttribute('aria-expanded', String(isOpen)); }); document.addEventListener('click', event => { if (!menu.contains(event.target)) closeMenu(); }); }
document.addEventListener('DOMContentLoaded', async () => { await Promise.all([loadComponent('navbar', 'navbar.html'), loadComponent('footer', 'footer.html')]); renderAccountActions(); const activeLink = document.querySelector(`.site-nav a[href="${location.pathname.split('/').pop() || 'index.html'}"]`); if (activeLink) { activeLink.style.fontWeight = '800'; activeLink.style.color = 'var(--primary)'; } document.querySelector('.menu-toggle')?.addEventListener('click', () => document.querySelector('.site-nav')?.classList.toggle('open')); });
